version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: patroliku_admin_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: patroliku_admin_nginx
    ports:
      - "8383:80"   # ⬅️ PORT DIUBAH DI SINI
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
